#!/usr/local/bin/bash

# get options from command line
while getopts :rluh option
do 
    case "${option}"
        in
        r) 
            ;;
        l) 
            ;;
        u) 
            ;;
        h) 
            echo "Example usage:"
            echo "modify [OPTION] [SED PATTERN] <dir/file names...>"
            echo "Program modifies file names."
            echo 
            echo "Option:"
            echo "-r   use recursion"
            echo "-l   lowerize file names"
            echo "-u   uppercase file names"
            echo "-h   display help"
            echo
            ;;
        ?) 
            echo "Unknown parameter. Use -h for help."
            echo
            ;;
    esac
done