#!/usr/local/bin/bash

# default options
do_recursion=false
do_lower=false
do_upper=false

# get options from command line
while getopts rluh option
do 
    case "${option}"
        in
        r) 
            # recursion
            do_recursion=true
            ;;
        l) 
            # lowerizing
            do_lower=true
            ;;
        u) 
            #uppercasing
            do_upper=true
            ;;
        h) 
            #help
            echo "Example usage:"
            echo "modify [OPTION] [SED PATTERN] <dir/file names...>"
            echo "Program modifies file names."
            echo 
            echo "Options:"
            echo "-r   use recursion"
            echo "-l   lowerizing file names"
            echo "-u   uppercasing file names"
            echo "-h   display help"
            echo
            # end program
            exit
            ;;
        ?) 
            # other
            echo "Unknown option. Use -h for help."
            echo
            # end program
            exit
            ;;
    esac
done

# remove all options that have been parsed by getopts
shift "$((OPTIND-1))"

# see if parameters are correct
if $do_upper && $do_lower; then
    echo "Incorrect options. Use -h for help."
    echo
    # end program
    exit
fi
